export type SystemTier = 1 | 2 | 3;
export type SystemCategory =
  | "official"
  | "efficiency"
  | "margin"
  | "human_poll"
  | "composite"
  | "independent";

export interface MasseySystem {
  code: string;
  fullName: string;
  tier: SystemTier;
  category: SystemCategory;
  description: string;
  usedInModel: boolean;
  weight?: number;
}

export const MASSEY_SYSTEMS: MasseySystem[] = [
  {
    code: "POM",
    fullName: "KenPom",
    tier: 1,
    category: "efficiency",
    usedInModel: true,
    weight: 0.25,
    description:
      "Tempo-adjusted offensive + defensive efficiency per 100 possessions. Gold standard for tournament prediction. Created by Ken Pomeroy.",
  },
  {
    code: "NET",
    fullName: "NCAA Evaluation Tool",
    tier: 1,
    category: "official",
    usedInModel: true,
    weight: 0.2,
    description:
      "Official NCAA committee metric since 2019. Weights wins by opponent quality and game location. Directly used for seeding decisions.",
  },
  {
    code: "SAG",
    fullName: "Sagarin Ratings",
    tier: 1,
    category: "margin",
    usedInModel: true,
    weight: 0.15,
    description:
      'One of the oldest computer ratings. Margin-of-victory based. "Predictor" variant (pure efficiency) is best for game outcome prediction.',
  },
  {
    code: "BPI",
    fullName: "ESPN Basketball Power Index",
    tier: 1,
    category: "efficiency",
    usedInModel: true,
    weight: 0.12,
    description:
      "ESPN's proprietary pace-adjusted efficiency metric. Good for upset detection. Accounts for home/away and key injuries.",
  },
  {
    code: "RPI",
    fullName: "Rating Percentage Index",
    tier: 1,
    category: "composite",
    usedInModel: true,
    weight: 0.08,
    description:
      "Legacy NCAA metric (pre-2019): 25% team win%, 50% opponent win%, 25% opp-of-opp win%. Less accurate than NET but 30+ years of historical data.",
  },
  {
    code: "MAS",
    fullName: "Massey Ratings",
    tier: 1,
    category: "margin",
    usedInModel: true,
    weight: 0.08,
    description:
      "Ken Massey's own least-squares margin-based system — the math behind our primary Massey feature. Validates our in-model calculation.",
  },
  {
    code: "COL",
    fullName: "Colley Matrix",
    tier: 1,
    category: "margin",
    usedInModel: true,
    weight: 0.05,
    description:
      "Pure win/loss, no margin of victory. Solves simultaneous linear equations. Good robustness signal when margin data is noisy.",
  },
  {
    code: "WOL",
    fullName: "Wolfe Ratings",
    tier: 1,
    category: "composite",
    usedInModel: true,
    weight: 0.04,
    description: "Win/loss + strength of schedule. Independent system with solid track record.",
  },
  {
    code: "AP",
    fullName: "AP Poll",
    tier: 1,
    category: "human_poll",
    usedInModel: true,
    weight: 0.02,
    description:
      'Associated Press human media poll. Captures narrative bias and team reputation. The gap between AP rank and computer consensus = "hype tax" signal.',
  },
  {
    code: "USA",
    fullName: "Coaches Poll",
    tier: 1,
    category: "human_poll",
    usedInModel: true,
    weight: 0.01,
    description:
      "Coaches vote on top 25. Coaches systematically underrate teams they haven't faced. Conference blind spots make this a useful contrarian signal.",
  },
  {
    code: "WAB",
    fullName: "Wins Above Bubble",
    tier: 1,
    category: "composite",
    usedInModel: true,
    weight: 0.1,
    description:
      "BartTorvik metric: how many wins above a theoretical bubble team. Best measure of tournament-worthiness vs raw quality. Higher = more deserving.",
  },
  {
    code: "STH",
    fullName: "Seth Burns Power Ratings",
    tier: 2,
    category: "independent",
    usedInModel: false,
    description: "Well-regarded independent ratings with good long-term track record.",
  },
  {
    code: "DOL",
    fullName: "Dolphin Ratings",
    tier: 2,
    category: "margin",
    usedInModel: false,
    description: "Margin-of-victory based, similar methodology to Sagarin.",
  },
  {
    code: "SRS",
    fullName: "Simple Rating System",
    tier: 2,
    category: "margin",
    usedInModel: false,
    description: "Sports Reference's clean margin + SOS system. Interpretable and well-documented.",
  },
  {
    code: "DC",
    fullName: "Dunkel Index",
    tier: 2,
    category: "independent",
    usedInModel: false,
    description: "Established computer system with long history in college football and basketball.",
  },
  {
    code: "RTH",
    fullName: "Real-Time RPI",
    tier: 2,
    category: "composite",
    usedInModel: false,
    description: "Continuous RPI update during the season. More current than end-of-season RPI.",
  },
  {
    code: "MPI",
    fullName: "Massey Predictive Index",
    tier: 2,
    category: "margin",
    usedInModel: false,
    description: "Ken Massey's best-performing predictive variant of his rating system.",
  },
  ...(
    [
      "ACU",
      "ADE",
      "AEI",
      "ARG",
      "ATP",
      "AUS",
      "AWS",
      "BAR",
      "BBT",
      "BD",
      "BIH",
      "BKM",
      "BLS",
      "BMN",
      "BNM",
      "BNT",
      "BNZ",
      "BOB",
      "BOW",
      "BP5",
      "BRZ",
      "BWE",
      "CBR",
      "CJB",
      "CMV",
      "CNG",
      "COX",
      "CRO",
      "CRW",
      "CTL",
      "CWL",
      "DAV",
      "DDB",
      "DES",
      "DII",
      "DOK",
      "DUN",
      "DWH",
      "EBB",
      "EBP",
      "ECK",
      "EMK",
      "ENG",
      "ENT",
      "ERD",
      "ESR",
      "FAS",
      "FDM",
      "FMG",
      "FSH",
      "GC",
      "GRN",
      "GRS",
      "HAS",
      "HAT",
      "HER",
      "HKB",
      "HKS",
      "HOL",
      "HRN",
      "IMS",
      "INC",
      "INP",
      "ISR",
      "JCI",
      "JEN",
      "JJK",
      "JNG",
      "JON",
      "JRT",
      "KBM",
      "KCX",
      "KEL",
      "KLK",
      "KMV",
      "KOS",
      "KPI",
      "KPK",
      "KRA",
      "LAB",
      "LAW",
      "LEF",
      "LMC",
      "LOG",
      "LYD",
      "LYN",
      "MB",
      "MCL",
      "MGS",
      "MGY",
      "MIC",
      "MKV",
      "MMG",
      "MOR",
      "MSX",
      "MUZ",
      "MvG",
      "NOL",
      "NOR",
      "OCT",
      "OMN",
      "OMY",
      "PAC",
      "PEQ",
      "PGH",
      "PH",
      "PIG",
      "PIR",
      "PKL",
      "PMC",
      "PPR",
      "PRR",
      "PTS",
      "RAG",
      "REI",
      "REN",
      "REW",
      "RIS",
      "RM",
      "RME",
      "RMS",
      "ROG",
      "ROH",
      "RSE",
      "RSL",
      "RT",
      "RTB",
      "RTP",
      "RTR",
      "RWP",
      "SAP",
      "SAU",
      "SCR",
      "SE",
      "SEL",
      "SFX",
      "SGR",
      "SIM",
      "SMN",
      "SMS",
      "SP",
      "SPR",
      "SPW",
      "STF",
      "STM",
      "STR",
      "STS",
      "STY",
      "TBD",
      "TBL",
      "TMR",
      "TOL",
      "TPR",
      "TRK",
      "TRP",
      "TRX",
      "TS",
      "TSR",
      "TW",
      "UCS",
      "UPS",
      "WEI",
      "WIL",
      "WLK",
      "WLS",
      "WMR",
      "WMV",
      "WOB",
      "WTE",
      "YAG",
      "ZAM",
    ] as const
  ).map(
    (code): MasseySystem => ({
      code,
      fullName: code,
      tier: 3,
      category: "independent",
      usedInModel: false,
      description:
        "Independent/minor rating system. Used only as part of consensus average across all 150+ systems.",
    }),
  ),
];

export const TIER1_SYSTEMS = MASSEY_SYSTEMS.filter((s) => s.tier === 1);
export const MODEL_SYSTEMS = MASSEY_SYSTEMS.filter((s) => s.usedInModel);

export function getSystem(code: string): MasseySystem | undefined {
  return MASSEY_SYSTEMS.find((s) => s.code === code);
}

export const CONSENSUS_COMPUTER_SYSTEMS = ["POM", "SAG", "NET", "BPI", "MAS", "COL", "WOL"];

/** Systems shown in predictor “System rankings” table (Tier 1 subset with clear labels). */
export const PREDICTOR_ORDINAL_CODES: string[] = [
  "POM",
  "NET",
  "SAG",
  "BPI",
  "RPI",
  "MAS",
  "COL",
  "WOL",
  "WAB",
  "AP",
  "USA",
];
