/**
 * Map The Odds API full team strings → Kaggle `TeamName` from our API.
 * Keys are normalized lowercase in `oddsNameToKaggle`.
 */
export const ODDS_TO_KAGGLE: Record<string, string> = {
  "duke blue devils": "Duke",
  "north carolina tar heels": "North Carolina",
  "michigan wolverines": "Michigan",
  "kentucky wildcats": "Kentucky",
  "michigan state spartans": "Michigan St",
  "michigan state": "Michigan St",
  "michigan st": "Michigan St",
  "connecticut huskies": "UConn",
  connecticut: "UConn",
  "uconn huskies": "UConn",
  uconn: "UConn",
  "houston cougars": "Houston",
  "iowa state cyclones": "Iowa St",
  "florida gators": "Florida",
  "arizona wildcats": "Arizona",
  "gonzaga bulldogs": "Gonzaga",
  "kansas jayhawks": "Kansas",
  "illinois fighting illini": "Illinois",
  "virginia cavaliers": "Virginia",
  "byu cougars": "BYU",
  "ucla bruins": "UCLA",
  "ohio state buckeyes": "Ohio St",
  "tennessee volunteers": "Tennessee",
  "st. john's red storm": "St John's",
  "st johns red storm": "St John's",
  "iowa hawkeyes": "Iowa",
  "texas tech red raiders": "Texas Tech",
  "louisville cardinals": "Louisville",
  "purdue boilermakers": "Purdue",
  "arkansas razorbacks": "Arkansas",
  "nebraska cornhuskers": "Nebraska",
  "alabama crimson tide": "Alabama",
  "auburn tigers": "Auburn",
  "wisconsin badgers": "Wisconsin",
  "vanderbilt commodores": "Vanderbilt",
  vanderbilt: "Vanderbilt",
  "clemson tigers": "Clemson",
  "baylor bears": "Baylor",
  "texas longhorns": "Texas",
  "marquette golden eagles": "Marquette",
  "creighton bluejays": "Creighton",
  "san diego state aztecs": "San Diego St",
  "florida atlantic owls": "FAU",
  "drake bulldogs": "Drake",
  "mcneese cowboys": "McNeese",
  "james madison dukes": "James Madison",
  "grand canyon antelopes": "Grand Canyon",
  "colorado buffaloes": "Colorado",
  "memphis tigers": "Memphis",
  "texas a&m aggies": "Texas A&M",
  "maryland terrapins": "Maryland",
  "mississippi st bulldogs": "Mississippi St",
  "washington huskies": "Washington",
  "san francisco dons": "San Francisco",
  "utah state aggies": "Utah St",
  "utah state": "Utah St",
  "new mexico lobos": "New Mexico",
  "nevada wolf pack": "Nevada",
  "dayton flyers": "Dayton",
  "northwestern wildcats": "Northwestern",
  "south carolina gamecocks": "South Carolina",
  "oklahoma sooners": "Oklahoma",
  "miami hurricanes": "Miami FL",
  "xavier musketeers": "Xavier",
  "providence friars": "Providence",
  "seton hall pirates": "Seton Hall",
  "villanova wildcats": "Villanova",
  villanova: "Villanova",
  "west virginia mountaineers": "West Virginia",
  "cincinnati bearcats": "Cincinnati",
  "tcu horned frogs": "TCU",
  "georgetown hoyas": "Georgetown",
  "pittsburgh panthers": "Pittsburgh",
  "syracuse orange": "Syracuse",
  "notre dame fighting irish": "Notre Dame",
  "florida state seminoles": "Florida St",
  "georgia bulldogs": "Georgia",
  "lsu tigers": "LSU",
  "ole miss rebels": "Mississippi",
  "mount st. mary's mountaineers": "Mount St Mary's",
  "longwood lancers": "Longwood",
  "wagner seahawks": "Wagner",
  "howard bison": "Howard",
  "grambling tigers": "Grambling",
  "st. mary's gaels": "St Mary's CA",
  "st mary's gaels": "St Mary's CA",
  "miami (oh) redhawks": "Miami OH",
  "south florida bulls": "South Florida",
  "northern iowa panthers": "Northern Iowa",
  "queens royals": "Queens NC",
  "liu sharks": "LIU Brooklyn",
  "prairie view a&m panthers": "Prairie View",
  "umbc retrievers": "UMBC",
  "cal baptist lancers": "Cal Baptist",
  "north dakota state bison": "N Dakota St",
  "wright state raiders": "Wright St",
  "tennessee state tigers": "Tennessee St",
  "hofstra pride": "Hofstra",
  "high point panthers": "High Point",
  "kennesaw state owls": "Kennesaw",
  "penn quakers": "Penn",
  "santa clara broncos": "Santa Clara",
  "ucf knights": "UCF",
  "idaho vandals": "Idaho",
  "lehigh mountain hawks": "Lehigh",
  // 2026 bracket additions
  "missouri tigers": "Missouri",
  "saint mary's gaels": "Saint Mary's",
  "saint louis billikens": "Saint Louis",
  "furman paladins": "Furman",
  "siena saints": "Siena",
  "troy trojans": "Troy",
  "akron zips": "Akron",
  "hawaii rainbow warriors": "Hawaii",
  "long island sharks": "Long Island",
};

export function oddsNameToKaggle(oddsName: string | null | undefined): string | null {
  if (oddsName == null || typeof oddsName !== "string") return null;
  const norm = oddsName.toLowerCase().trim();
  if (ODDS_TO_KAGGLE[norm]) return ODDS_TO_KAGGLE[norm];
  const simple = norm.replace(/\s+(university|univ\.?|college)\b.*$/i, "").trim();
  if (ODDS_TO_KAGGLE[simple]) return ODDS_TO_KAGGLE[simple];
  return null;
}

export function kaggleToOddsName(kaggleName: string): string | null {
  const entry = Object.entries(ODDS_TO_KAGGLE).find(([, v]) => v === kaggleName);
  return entry ? entry[0] : null;
}
